'use strict';const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),sprites=require('../assets/icon-sprites-v2.js');const root=path.resolve(__dirname,'..'),mn=fs.readdirSync(path.join(root,'assets/icons/v2')).find(n=>/^icon-manifest\.[0-9a-f]{12}\.json$/.test(n)),manifest=JSON.parse(fs.readFileSync(path.join(root,'assets/icons/v2',mn)));
test('normalisation and +4 parsing',()=>{assert.equal(sprites.normaliseName('Merchant’s Coffer'),'merchants coffer');assert.deepEqual(sprites.splitGearName('Copper Sword +4'),{original:'Copper Sword +4',base:'Copper Sword',upgrade:4});});
test('every overlay and alias resolves',()=>{let r=sprites.createResolver(manifest);for(let n=1;n<=4;n++){let x=r.gear('Copper Sword+'+n);assert.ok(x.base);assert.ok(x.overlay);}for(let k of Object.keys(manifest.gear.aliases))assert.ok(r.gear(k).base,k);});
test('all item IDs and shared cells resolve',()=>{let r=sprites.createResolver(manifest);for(let id of Object.keys(manifest.items.icons))assert.ok(r.item(id),id);assert.deepEqual(r.item('copper_atk_potion'),r.item('iron_atk_potion'));});
test('chunk cache deduplicates requests',async()=>{let calls=0,key=Object.keys(manifest.chunks)[0],c=sprites.createChunkCache(manifest,'./m.json',{baseUrl:'https://x/a/',loadImage:async()=>{calls++;return{};}});await Promise.all([c.load(key),c.load(key)]);assert.equal(calls,1);});
class CL{constructor(x){this.x=new Set(x);}contains(x){return this.x.has(x);}add(x){this.x.add(x);}}
class L{constructor(){this.style={};this.a={};}setAttribute(k,v){this.a[k]=String(v);}}
class H{constructor(type,a){this.nodeType=1;this.isConnected=true;this.a={...a};this.classList=new CL([type==='g'?'iw-gear-sprite-host':'iw-item-sprite-host']);this.base=new L();this.up=type==='g'?new L():null;}getAttribute(k){return this.a[k]||null;}setAttribute(k,v){this.a[k]=String(v);}removeAttribute(k){delete this.a[k];}querySelector(s){return s.includes('sprite-base')?this.base:s.includes('sprite-upgrade')?this.up:null;}querySelectorAll(){return [];}matches(s){return(s.includes('gear')&&this.classList.contains('iw-gear-sprite-host'))||(s.includes('item')&&this.classList.contains('iw-item-sprite-host'));}}
function browser(hosts){let state={fetches:0,images:[]},doc={baseURI:'https://example.test/',documentElement:{},querySelectorAll:()=>hosts};class IO{constructor(cb,o){this.cb=cb;this.options=o;this.observed=[];state.io=this;}observe(h){this.observed.push(h);}unobserve(h){this.observed=this.observed.filter(x=>x!==h);}}class MO{constructor(cb){this.cb=cb;state.mo=this;}observe(){}}state.win={document:doc,IntersectionObserver:IO,MutationObserver:MO,requestAnimationFrame:f=>f(),fetch:async()=>{state.fetches++;return{ok:true,json:async()=>manifest};}};return state;}async function settle(){await new Promise(r=>setImmediate(r));await new Promise(r=>setImmediate(r));}
test('hidden hosts request nothing',()=>{let g=new H('g',{'data-iw-gear-sprite':'Copper Sword+4'}),s=browser([g]);sprites.install(s.win,{manifestUrl:'./assets/icons/v2/'+mn,loadImage:async u=>{s.images.push(u);return{};}});assert.equal(s.fetches,0);assert.equal(s.images.length,0);assert.equal(s.io.options.rootMargin,'300px 0px');});
test('gear and item tooltip hosts load correct chunks',async()=>{let g=new H('g',{'data-iw-gear-sprite':'Lapidary Gloves+4'}),i=new H('i',{'data-iw-item-sprite':'copper_atk_potion'}),s=browser([g,i]);sprites.install(s.win,{manifestUrl:'./assets/icons/v2/'+mn,loadImage:async u=>{s.images.push(u);return{};}});s.io.cb([{isIntersecting:true,target:g},{isIntersecting:true,target:i}]);await settle();assert.equal(g.a['data-iw-sprite-state'],'ready');assert.equal(g.up.a['data-iw-upgrade-state'],'ready');assert.equal(i.a['data-iw-item-sprite-state'],'ready');assert.match(g.base.style.backgroundImage,/gloves\.[0-9a-f]{12}/);assert.match(g.up.style.backgroundImage,/overlays\.[0-9a-f]{12}/);assert.match(i.base.style.backgroundImage,/consumables\.[0-9a-f]{12}/);});
test('failed chunk leaves fallback state',async()=>{let i=new H('i',{'data-iw-item-sprite':'copper_ore'}),s=browser([i]);sprites.install(s.win,{manifestUrl:'./assets/icons/v2/'+mn,loadImage:async()=>{throw Error('offline');}});s.io.cb([{isIntersecting:true,target:i}]);await settle();assert.equal(i.a['data-iw-item-sprite-state'],'error');});
